### ISSUE TITLE
failed user login is not handled correctly

### ISSUE THREAD

**Issue by karenetheridge** [joyent/conch-ui#262] opened 2020-09-24 21:40 UTC
As discussed in MM last week -- when the user enters an invalid password at the login page, the 401 response is being sent back to the browser which kicks up a default user auth form.

![Screen Shot 2020-09-24 at 2 37 41 PM](https://user-images.githubusercontent.com/303051/94203122-afa8f080-fe73-11ea-9b35-08d4583cf670.png)

**Comment by dustinryerson** [comment] 2020-10-12 17:37
This is being caused by the `WWW-Authenticate` header being returned in the response, which was added to the API here: https://github.com/joyent/conch-api/pull/985

**Comment by dustinryerson** [comment] 2020-12-23 00:39
This issue has been resolved by https://github.com/joyent/conch-api/pull/1042.

**Closed by dustinryerson** 2020-12-23 00:39 UTC
Labels: bug, wat
